### ISSUE TITLE
about api's documents

### ISSUE THREAD

**Issue by da0shi** [givery-technology/etc#7]
Are we going to use some documentation format for API document?  Such as RAML or JSON Schema.
Or, use test code as a document and don't use any other documents.

I think I have asked same question before, and you have answered that you are not thinking about using document format other than test code. But to make sure of it.

**Comment by shunjikonishi** [comment]
I'm now developing a framework for writing API specification as a test.

https://github.com/shunjikonishi/api-first-spec

Maybe it can use soon.   

With this framework, we can write API specification like this.

https://github.com/shunjikonishi/api-first-spec/blob/master/test/login.spec.js

**Comment by da0shi** [comment]
I see :+1:
thank you for the answer.
